### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by nikolicdragan** [ThematoSoup/Gumbo#58]
http://gumbotheme.com/comments/
1. Clicking on a date of a comment does something I didn't expect, where Sticky Header covers the comment.
2. Name, date and comment text could look better. 
   
   2.a. Comments should not have the same font size V contrast as post text.
   
   2.b. Comment text >= Name > Date
   
   2.c. Not sure whether dates should be links. I know that's the default behavior, but why?
3. Admins, authors & contributors' comments should differ than those of visitors'.

**Comment by slobodan** [comment]
1 - Not something we can fix. Clicking the date takes you to portion of the page where that comment is on top of the page (so a certain comment can be bookmarked or linked to). Sticky header is also shown on top. If anything this is Sticky Header issue, but let's leave as is, for now at least.

2.a - Made them smaller.
2.b - Made some changes, I think it will do.
2.c - Explained.

3 - Comments by post author are highlighted (from my local installation - http://cl.ly/image/3H2D20073f30). Looking at demo site code, none of these comments have .bypostauthor class, probably because they were imported with demo content and not actually added by post author.

Not sure if we should keep the comments we have in that post. Those ones are for testing purposes, for demo site, we should probably have something that looks more like a real discussion.

**Comment by nikolicdragan** [comment]
Can you increase spacing between the reply button and the adjacent comment, so there's no confusion?

![comments-enhacement](https://f.cloud.github.com/assets/2678265/1923632/eeb31cd0-7e17-11e3-8104-ad7a79ae496a.png)

**Comment by nikolicdragan** [comment]
Author Comment - Can you make it more distinguishable?

![author-comments](https://f.cloud.github.com/assets/2678265/1923734/3790ded2-7e19-11e3-87c6-e94d856c7912.jpg)

**Comment by slobodan** [comment]
How? Suggest something.

---

_Slobodan Manic_
@ http://twitter.com/slobodanmanicslobodanmanichttp://twitter.com/slobodanmanic

**Comment by nikolicdragan** [comment]
How about we make that border more visible... similar to what you did on contact 7 fields. I think it's easier to do that than make background color adjustments (because you have 3 color schemes to consider)

Bear in mind the dark color scheme.
